export const ringLabel=i=>['정면 0°','오른쪽 30°','오른쪽 60°','오른쪽 90°','오른쪽 뒤 120°','오른쪽 뒤 150°','뒤 180°','왼쪽 뒤 150°','왼쪽 뒤 120°','왼쪽 90°','왼쪽 60°','왼쪽 30°'][i];
export function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
export function rng(seed){let a=hash(seed);return()=>{a+=0x6D2B79F5;let t=Math.imul(a^a>>>15,a|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function makePlan(clips,c){const random=rng(c.seed),available=clips.filter(x=>x.dataset===c.dataset&&(c.sound==='both'||x.kind===c.sound)&&!x.reference);if(!available.length)throw Error('선택한 조건에 음원이 없습니다.');const shuffle=list=>{for(let i=list.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;};let trials=[];if(c.dataset==='trajectory'){const selected=c.mode==='practice'?shuffle([...available]).slice(0,4):available;for(const clip of selected)for(let stage=1;stage<=3;stage++)trials.push({clipId:clip.id,repeat:1,stage});if(c.mode!=='practice')shuffle(trials);}else{for(let r=0;r<c.repeats;r++)for(const clip of available)trials.push({clipId:clip.id,repeat:r+1});shuffle(trials);if(c.mode==='practice')trials=trials.slice(0,4);}return trials.map((t,i)=>({...t,number:i+1,plays:[]}));}
export const angularError=(a,b)=>Math.min(Math.abs(a-b)%360,360-Math.abs(a-b)%360);
export function score(clip,answer){const step=clip.dataset==='ring'?30:clip.dataset==='ring8'?45:null;return{correct:clip.targetIndex===answer,angularErrorDeg:step?angularError(clip.targetIndex*step,answer*step):null};}
export function csv(rows){if(!rows.length)return '\uFEFF';const keys=Object.keys(rows[0]);const cell=v=>{let s=v==null?'':String(v);if(typeof v!=='number'&&/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\uFEFF'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
export const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
export const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.floor(b.length/2);return b.length%2?b[i]:(b[i-1]+b[i])/2;};
